# flake8: noqa
# Generated by Django 4.2.26 on 2025-12-01 22:58

import cloudinary.models
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='bloggerrequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='about',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloggerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloggerprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='bloggerrequest',
            name='reason',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
