# Generated by Django 4.2.26 on 2025-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bloggerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
