"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-c8=d-b8^&45w+zkj(*2i+h)o72q!h=v%n_ahlr$3n64novxsw2'

# SECURITY WARNING: don't run with debug turned on in production!
import os

# Monkeypatch for bleach.clean compatibility: some versions of django_summernote
# call bleach.clean(..., styles=...), which newer bleach versions don't accept.
# Make a permissive wrapper during startup so migrations/management commands run.
try:
    import bleach
    _bleach_clean = bleach.clean
    def _bleach_clean_compat(text, *args, **kwargs):
        # Some callers may pass None; coerce to empty string for sanitizer.
        if text is None:
            return ''
        kwargs.pop('styles', None)
        return _bleach_clean(text, *args, **kwargs)
    bleach.clean = _bleach_clean_compat
except Exception:
    # If bleach isn't available or patching fails, continue — errors will surface later.
    pass

# Load local env.py if present (developer convenience). Keep using os.path.isfile.
if os.path.isfile("env.py"):
    try:
        import env  # optional local overrides (defines SECRET_KEY, etc.)
    except Exception:
        # If env.py exists but fails to import, continue with environment variables
        pass
    DEBUG = True
else:
    DEBUG = False

# Secret key should come from env or environment variable in production
SECRET_KEY = os.environ.get('SECRET_KEY')





ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.herokuapp.com',
]


# For development: print emails to console
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_summernote',
]

# Cloudinary apps only when configured to avoid import-time errors in dev
if os.environ.get('CLOUDINARY_URL') or os.environ.get('CLOUDINARY_API_KEY'):
    INSTALLED_APPS += [
        'cloudinary',
        'cloudinary_storage',
    ]

# Project apps
INSTALLED_APPS += [
    'users.apps.UsersConfig',  # keep this
    'core',
    'blog',
    'bookings',
    'services',
    'accounts',
    'cart',
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.codeinstitute-ide.net/",
    "https://*.herokuapp.com"
]
# -------------------------------
# Custom user model
# -------------------------------
AUTH_USER_MODEL = 'users.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Optional: Postgres configuration (enable by setting USE_POSTGRES env var
# to '1' or providing a DATABASE_URL). Keeps SQLite as a safe default.
_use_postgres_flag = os.environ.get('USE_POSTGRES', '')
_db_url = os.environ.get('DATABASE_URL')

if (_use_postgres_flag and str(_use_postgres_flag).lower() in ('1', 'true', 'yes')) or _db_url:
    # Prefer full DATABASE_URL when available and use dj-database-url if installed.
    try:
        import dj_database_url

        DATABASES['default'] = dj_database_url.config(
            env='DATABASE_URL',
            default=_db_url,
            conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', 600)),
            ssl_require=os.environ.get('DB_SSL_REQUIRE', '1').lower() in ('1', 'true', 'yes'),
        )
    except Exception:
        # Fallback: if DATABASE_URL present, parse it with urllib; otherwise use DB_* vars
        if _db_url:
            from urllib.parse import urlparse

            _p = urlparse(_db_url)
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': _p.path[1:] if _p.path else '',
                'USER': _p.username,
                'PASSWORD': _p.password,
                'HOST': _p.hostname,
                'PORT': _p.port or '5432',
            }
        else:
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('DB_NAME', 'capstone_db'),
                'USER': os.environ.get('DB_USER', 'capstone_user'),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'HOST': os.environ.get('DB_HOST', 'localhost'),
                'PORT': os.environ.get('DB_PORT', '5432'),
            }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_DIRS = [os.path.join(BASE_DIR, 'static')]


# Whitenoise static file serving    
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type    
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if os.environ.get('CLOUDINARY_URL') or os.environ.get('CLOUDINARY_API_KEY'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    # Use local filesystem storage in development when Cloudinary is not configured
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'