# Generated by Django 4.2.26 on 2025-12-08 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='service_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='services.service',
            ),
        ),
        migrations.AddField(
            model_name='booking',
            name='size',
            field=models.CharField(
                choices=[
                    ('small', 'Small'),
                    ('medium', 'Medium'),
                    ('large', 'Large'),
                ],
                default='small',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='services.service',
            ),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(
                choices=[
                    ('small', 'Small'),
                    ('medium', 'Medium'),
                    ('large', 'Large'),
                ],
                default='small',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bookings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cart_items',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
